apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: siak-system
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      terminationGracePeriodSeconds: 3

      #"HA + scalable"
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "ScheduleAnyway"
          labelSelector:
            matchLabels:
              app: laravel-app

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "role"
                    operator: "In"
                    values:
                      - worker

      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 3
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 3

      containers:
        - name: laravel-app
          image: docker.io/saka8631/laravel-siak:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: laravel-env

