apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: siak-system
data:
  default.conf: |
    upstream laravel_upstream {
        least_conn;
        server laravel-service:9000;
    }

    server {
        listen 80;
        server_name _;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            #fastcgi_pass 192.168.1.3:9000;
            fastcgi_pass laravel_upstream;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }
